---
#-- Enable Percona Release
  - name: Install percona-release package Debian Noble
    shell: |
      wget https://repo.percona.com/apt/percona-release_latest.generic_all.deb
      apt install ./percona-release_latest.generic_all.deb
      apt update
    when: ansible_os_family == "Debian" and ansible_distribution_release == "noble"

  - name: Install percona-release package Debian
    apt:
      deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    when: ansible_os_family == "Debian" and ansible_distribution_release != "noble"

#-- Enable Testing Repo
  - name: Install percona repository package for Debain
    apt:
      deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    when: ansible_os_family == "Debian"

  - name: Add ARM support into percona-release
    shell: sed -i "s|x86_64|x86_64 aarch64|" /usr/bin/percona-release
    when: ansible_architecture == "aarch64" or ansible_architecture == "arm64"

  - name: enable the PS-84-LTS testing repo
    command: percona-release enable-only ps-84-lts testing

  - name: enable the pxb-84 release repo
    command: percona-release enable pxb-84-lts release
    when: ansible_distribution_release == "noble"

  - name: install Percona Server deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-server-server{{ pro_suf | default('') }}
      - percona-server-test{{ pro_suf | default('') }}
      - percona-server{{ pro_suf | default('') }}-dbg
      - percona-server{{ pro_suf | default('') }}-source
      - percona-server-client{{ pro_suf | default('') }}
      - percona-server-rocksdb{{ pro_suf | default('') }}
      - percona-mysql-router{{ pro_suf | default('') }}
    when: ansible_os_family == "Debian"
    environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

  - name: download and extract world database
    command: "{{ item }}"
    with_items:
    - wget --no-check-certificate -P /package-testing https://raw.githubusercontent.com/Percona-QA/percona-qa/master/sample_db/world.sql

  - name: start mysql service
    service: name=mysql state=started

  - name: install percona-mysql-shell package for Debian/Ubuntu
    apt:
      update_cache: yes
      state: present
      name: "{{ packages }}"
    vars:
      packages:
      - percona-mysql-shell
    when: ansible_os_family == "Debian"
