---
- name: Prepare environment and install MySQL Server
  hosts: all
  become: yes
  tasks:

    - name: Ensure required packages are installed
      ansible.builtin.package:
        name:
          - wget
          - gnupg
        state: present

    - name: Add MySQL APT repository
      ansible.builtin.shell:
        cmd: |
          wget https://dev.mysql.com/get/mysql-apt-config_0.8.26-1_all.deb
          dpkg -i mysql-apt-config_0.8.26-1_all.deb
        args:
          creates: /etc/apt/sources.list.d/mysql.list

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
