---
- name: Prepare environment and install MySQL Server
  hosts: all
  become: yes
  tasks:

    - name: Ensure required packages are installed
      ansible.builtin.package:
        name:
          - wget
        state: present

    - name: Download MySQL APT configuration package
      ansible.builtin.get_url:
        url: https://dev.mysql.com/get/mysql-apt-config_0.8.26-1_all.deb
        dest: /tmp/mysql-apt-config.deb
        mode: '0644'

    - name: Install MySQL APT configuration package
      ansible.builtin.shell:
        cmd: dpkg -i /tmp/mysql-apt-config.deb
        executable: /bin/bash
