---
- name: Prepare node for running tests
  hosts: all
  become: true
  become_method: sudo
  gather_facts: true
  tasks:
    - name: Install Percona Server for MySQL
      ansible.builtin.apt:
        name:
          - percona-server-server
        state: present

    - name: Start and enable MySQL service
      ansible.builtin.systemd:
        name: mysql
        state: started
        enabled: yes
